### ISSUE TITLE
For AWSJobLimits we are using the bare SourceProxy class

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#50]
In debugging other problems with the conversion of spot_occupancy_config from a flat dictionary to a pandas data frame, I also noticed that the AWSJobLimits.py sourceis still getting information from aws_instance_limits which is a flat file written out by the publisher glideinwms/publishers/gwms_to_aws_data.py  in the previous channel channel_aws_config_data.conf

This should be examined and probably fixed.

**Comment by DmitryLitvintsev** [comment]
see https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/166

**Comment by StevenCTimm** [comment]
Some of the text got lost here--the initial bug report was not right, it turned out that we are using the bare SourceProxy class instead in production.  Presumably this will be looked at as part of the refactoring of the SourceProxy.

**Comment by StevenCTimm** [comment]
The bare source proxy class was getting called in this case because it's the only case in which 
a data block is picked from one channel.  channel_aws_config_data / datablock name aws_instance_limits
and being put into this channel as Job_Limits.

This functionality was preserved when SourceProxy was ported to the 1.3 releases.. the Dataproducts field
used to take a tuple but now it can take a tuple or a list.. lists are required in jsonnet land.

It should be looked at in the source proxy redesign if we still need this feature going forward.. It would not be too hard just to rename the data block to be the same everywhere, but there are some sources where
we need to use the same source to query two different htcondor installations and would like to call the data block a different name.. this might be accomplished by this method.

i.e. There is one source we are not running in the DE right now because it is not possible to call the "slots" source twice in the same channel, once to look at the user pool and once to look at the factory classads.. ditto it is not possible to call the "jobs" source twice in the same channel, once to look at the factory schedd's and once to look at the user schedd's.

**Comment by StevenCTimm** [comment]
This appears to have been fixed in the 2.0 release (by eliminating the SourceProxy altogether) and by changing the thing which calculates AWSJobLimits to be a transform rather than a source.  Will keep this open until 2.0 is released.

**Comment by StevenCTimm** [comment]
We are now running 2.0 everywhere so this issue is now moot.
