### ISSUE TITLE
Need to make glideinwms_request transform resilient against failure of dependent channels

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#78]
Right now if any of the other decision channels goes OFFLINE, the resource_request channel also goes offline/ The glideinwms_request transform that it contains CONSUMES everything and fails if any data block is not there.  Have to either harden all those channels so they never go OFFLINE, or rework the glideinwms_request transform so it can succeed with missing data.

**Comment by DmitryLitvintsev** [comment]
Imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/133

**Comment by DmitryLitvintsev** [comment]
To clarify--the source NerscJobInfo now is commented out and no longer runs, but there is another source NerscAllocationInfo which has the same problem.. this is even more ironic because that source only needs to run once a day.
It actually went offline on 10/25 and the old datablock is still showing as present from the channel, which is good.. but if we restart the DE at any point now then the whole of resource request will go offline too since we can't get a new value of this data block.

**Comment by DmitryLitvintsev** [comment]
timm @timm marked this issue as related to #110 3 months ago

**Comment by StevenCTimm** [comment]
I believe this will be addressed as part of the PRODUCES, CONSUMES logic revision that is scheduled for the framework.  In general the framework has to be involved.  Most of the modules have now been hardened by adding retries already but the hard-coded dependency where the glidein_requests.py CONSUMES everything will still have to be dealt with--either by more flexible configuration or by re-engineering the channel designs to allow more flexible concatenation of data blocks and allow for missing ones.  Tagging this as framework_req for now but could also be modules_req

**Comment by StevenCTimm** [comment]
In DE 2.0 there were two major changes made--one is that all previous 8 channels were combined all into
the resource_request channel ( although there may later be other channels added to deal with the non-pressure-based work).  
The second was that the 4 separate Factory_entries_xxxx blocks were unified into one Factory_Entries data block as had long been requested .

Nevertheless the issue is still there, just in a different form.  Now if one source goes offline they all do.  but the restart is much faster than it was before.
