### ISSUE TITLE
Future warnings from using pandas 0.23.4

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#98]
Current version on hepcsvc03 is 0.20.3.

Using the same configurations on the production de with pandas 0.23.4 we get the following Future Warnings:

/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/sources/factory_entries.py:70: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  dataframe = pandas.concat([dataframe, df], ignore_index=True)
/usr/lib/python2.7/site-packages/decisionengine_modules/AWS/transforms/FigureOfMerit.py:115: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  price_perf_df.reindex_axis(sorted(price_perf_df.columns), axis=1)
/usr/lib/python2.7/site-packages/decisionengine_modules/AWS/transforms/FigureOfMerit.py:117: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  fom_df.reindex_axis(sorted(fom_df.columns), axis=1)

**Comment by DmitryLitvintsev** [comment]
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/157

**Comment by StevenCTimm** [comment]
I note that all the reindex_axis functions have been replaced by reindex in the 1.1.1 branch.
The second warning about the sorting in 

/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/publishers/fe
_group_classads.py:72: FutureWarning: Sorting because non-concatenation axis is 
not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  publish_requests_df = pandas.DataFrame(pandas.concat(allow_type_req_dfs.values
(), ignore_index=True))

Has also gone away but it appears nothing was changed there.. keep this going until we have fully exercised the 1.1.x branch.

**Comment by StevenCTimm** [comment]
The second future warning came back as I expected it would

/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/sources/facto
ry_entries.py:75: FutureWarning: Sorting because non-concatenation axis is not a
ligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  dataframe = pandas.concat([dataframe, df], ignore_index=True)
/usr/lib64/python2.7/site-packages/pandas/core/frame.py:6211: FutureWarning: Sor
ting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

To be clear it is happening once in a module and once in pandas itself.

**Comment by DmitryLitvintsev** [comment]
https://fermicloud140.fnal.gov/reviews/r/103/
